-- MySQL Script generated by MySQL Workbench
-- 03/31/16 12:03:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema crf
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crf` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema laravel_base
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laravel_base
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laravel_base` DEFAULT CHARACTER SET utf8 ;
USE `crf` ;

-- -----------------------------------------------------
-- Table `crf`.`secuencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crf`.`secuencias` (
  `id_secuencia` INT NOT NULL,
  `clave` VARCHAR(5) NULL,
  `carrera` VARCHAR(45) NULL,
  PRIMARY KEY (`id_secuencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crf`.`edificios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crf`.`edificios` (
  `id_edificio` INT NOT NULL,
  `clave` VARCHAR(2) NULL,
  PRIMARY KEY (`id_edificio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crf`.`academias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crf`.`academias` (
  `id_academia` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `id_edificio` INT NOT NULL,
  PRIMARY KEY (`id_academia`, `id_edificio`),
  INDEX `fk_id_edificio_idx` (`id_edificio` ASC),
  CONSTRAINT `fk_id_edificio`
    FOREIGN KEY (`id_edificio`)
    REFERENCES `crf`.`edificios` (`id_edificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crf`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crf`.`materias` (
  `id_materia` INT NOT NULL,
  `clave` VARCHAR(10) NULL,
  `nombre` VARCHAR(100) NULL,
  `id_secuencia` INT NOT NULL,
  `id_academia` INT NOT NULL,
  PRIMARY KEY (`id_materia`, `id_secuencia`, `id_academia`),
  INDEX `fk_materias_secuencias1_idx` (`id_secuencia` ASC),
  INDEX `fk_materias_academias1_idx` (`id_academia` ASC),
  CONSTRAINT `fk_materias_secuencias1`
    FOREIGN KEY (`id_secuencia`)
    REFERENCES `crf`.`secuencias` (`id_secuencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materias_academias1`
    FOREIGN KEY (`id_academia`)
    REFERENCES `crf`.`academias` (`id_academia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crf`.`salones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crf`.`salones` (
  `id_salon` INT NOT NULL,
  `clave` VARCHAR(10) NULL,
  `id_edificio` INT NULL,
  PRIMARY KEY (`id_salon`, `id_edificio`),
  INDEX `fk_id_edificio1_idx` (`id_edificio` ASC),
  CONSTRAINT `fk_id_edificio1`
    FOREIGN KEY (`id_edificio`)
    REFERENCES `crf`.`edificios` (`id_edificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crf`.`dias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crf`.`dias` (
  `id_dia` INT NOT NULL,
  `clave` VARCHAR(1) NULL,
  `nombre` VARCHAR(9) NULL,
  PRIMARY KEY (`id_dia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crf`.`materias_salones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crf`.`materias_salones` (
  `id_materias_salones` INT NOT NULL,
  `id_materia` INT NOT NULL,
  `id_salon` INT NOT NULL,
  `id_dia` INT NOT NULL,
  PRIMARY KEY (`id_materias_salones`, `id_materia`, `id_salon`, `id_dia`),
  INDEX `fk_materias_salones_materias1_idx` (`id_materia` ASC),
  INDEX `fk_materias_salones_salones1_idx` (`id_salon` ASC),
  INDEX `fk_materias_salones_dias1_idx` (`id_dia` ASC),
  CONSTRAINT `fk_materias_salones_materias1`
    FOREIGN KEY (`id_materia`)
    REFERENCES `crf`.`materias` (`id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materias_salones_salones1`
    FOREIGN KEY (`id_salon`)
    REFERENCES `crf`.`salones` (`id_salon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materias_salones_dias1`
    FOREIGN KEY (`id_dia`)
    REFERENCES `crf`.`dias` (`id_dia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `laravel_base` ;

-- -----------------------------------------------------
-- Table `laravel_base`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_base`.`roles` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `slug` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `laravel_base`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_base`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(60) CHARACTER SET 'utf8' NOT NULL,
  `role_id` INT(10) UNSIGNED NOT NULL,
  `seen` TINYINT(1) NOT NULL DEFAULT '0',
  `valid` TINYINT(1) NOT NULL DEFAULT '0',
  `confirmed` TINYINT(1) NOT NULL DEFAULT '0',
  `confirmation_code` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `remember_token` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_username_unique` (`username` ASC),
  UNIQUE INDEX `users_email_unique` (`email` ASC),
  INDEX `users_role_id_foreign` (`role_id` ASC),
  CONSTRAINT `users_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `laravel_base`.`roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `laravel_base`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_base`.`posts` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `title` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `slug` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `summary` TEXT CHARACTER SET 'utf8' NOT NULL,
  `content` TEXT CHARACTER SET 'utf8' NOT NULL,
  `seen` TINYINT(1) NOT NULL DEFAULT '0',
  `active` TINYINT(1) NOT NULL DEFAULT '0',
  `user_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `posts_slug_unique` (`slug` ASC),
  INDEX `posts_user_id_foreign` (`user_id` ASC),
  CONSTRAINT `posts_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `laravel_base`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `laravel_base`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_base`.`comments` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `content` TEXT CHARACTER SET 'utf8' NOT NULL,
  `seen` TINYINT(1) NOT NULL DEFAULT '0',
  `user_id` INT(10) UNSIGNED NOT NULL,
  `post_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `comments_user_id_foreign` (`user_id` ASC),
  INDEX `comments_post_id_foreign` (`post_id` ASC),
  CONSTRAINT `comments_post_id_foreign`
    FOREIGN KEY (`post_id`)
    REFERENCES `laravel_base`.`posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `comments_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `laravel_base`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `laravel_base`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_base`.`contacts` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `text` TEXT CHARACTER SET 'utf8' NOT NULL,
  `seen` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `laravel_base`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_base`.`migrations` (
  `migration` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `batch` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `laravel_base`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_base`.`password_resets` (
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `token` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `password_resets_email_index` (`email` ASC),
  INDEX `password_resets_token_index` (`token` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `laravel_base`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_base`.`tags` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `tag` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tags_tag_unique` (`tag` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `laravel_base`.`post_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_base`.`post_tag` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `post_id` INT(10) UNSIGNED NOT NULL,
  `tag_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `post_tag_post_id_foreign` (`post_id` ASC),
  INDEX `post_tag_tag_id_foreign` (`tag_id` ASC),
  CONSTRAINT `post_tag_post_id_foreign`
    FOREIGN KEY (`post_id`)
    REFERENCES `laravel_base`.`posts` (`id`),
  CONSTRAINT `post_tag_tag_id_foreign`
    FOREIGN KEY (`tag_id`)
    REFERENCES `laravel_base`.`tags` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
